import torch

def permute(X: torch.Tensor, gather_indices: torch.Tensor, topk: int): ...
def unpermute(X: torch.Tensor, gather_indices: torch.Tensor): ...
def calculate_topk(gating_output: torch.Tensor, top_k: int, use_sigmoid: bool, renormalize: bool, pre_act: bool = True, post_act: bool = False): ...
def get_routing_indices(selected_experts, num_experts, return_scatter_indices: bool = False): ...
def torch_grouped_gemm(X, W, m_sizes, transpose: bool = True): ...
