from enum import Enum
from pydantic import BaseModel

class TokenClaims(BaseModel):
    iss: str = ...
    sub: str = ...
    exp: int = ...
    iat: int = ...
    jti: str = ...
    client_id: str = ...
    scopes: list[Enum] = ...
