from .registry import MODEL_REGISTRY as MODEL_REGISTRY, ModelInfo as ModelInfo, QuantType as QuantType

def register_models() -> None: ...
def search_models(org: str = None, base_name: str = None, version: str = None, size: str = None, quant_types: list[QuantType] = None, search_pattern: str = None) -> list[ModelInfo]: ...
