from _typeshed import Incomplete
from unsloth.registry.registry import ModelInfo as ModelInfo, ModelMeta as ModelMeta, QuantType as QuantType

class DeepseekV3ModelInfo(ModelInfo):
    @classmethod
    def construct_model_name(cls, base_name, version, size, quant_type, instruct_tag): ...

class DeepseekR1ModelInfo(ModelInfo):
    @classmethod
    def construct_model_name(cls, base_name, version, size, quant_type, instruct_tag): ...

DeepseekV3Meta: Incomplete
DeepseekV3_0324Meta: Incomplete
DeepseekR1Meta: Incomplete
DeepseekR1ZeroMeta: Incomplete
DeepseekR1DistillLlamaMeta: Incomplete
DeepseekR1DistillQwenMeta: Incomplete

def register_deepseek_v3_models(include_original_model: bool = False): ...
def register_deepseek_v3_0324_models(include_original_model: bool = False): ...
def register_deepseek_r1_models(include_original_model: bool = False): ...
def register_deepseek_r1_zero_models(include_original_model: bool = False): ...
def register_deepseek_r1_distill_llama_models(include_original_model: bool = False): ...
def register_deepseek_r1_distill_qwen_models(include_original_model: bool = False): ...
def register_deepseek_models(include_original_model: bool = False): ...
