from setuptools import setup, find_packages

setup(
    name="greeum",
    version="3.1.1rc3.dev2",
    description="Context-Dependent Neural Memory System for LLMs with GraphIndex beam search, STM/LTM consolidation, and semantic tagging",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="DryRainEnt",
    author_email="kachirjsdn@gmail.com",
    license="MIT",
    python_requires=">=3.10",
    packages=find_packages(exclude=("tests", "docs", "examples")),
    include_package_data=True,
    install_requires=[
        "rich>=13.4.0",
        "click>=8.1.0",
        "numpy>=1.24.0",
        "sqlalchemy>=2.0.0",
        "pydantic>=2.0.0",
        "anyio>=4.5",
        "requests>=2.25.0",
        "flask>=2.0.0",
        "flask-restx>=0.5.1",
        "flask-cors>=3.0.10",
        "python-dotenv>=0.19.0",
        "python-dateutil>=2.8.2",
        "sentence-transformers>=2.2.0",
        "psutil>=5.9.0",
        "fastapi>=0.110.0",
        "uvicorn[standard]>=0.22.0",
    ],
    extras_require={
        "test": ["pytest>=7.0", "pytest-cov", "responses>=0.23.0"],
        "dev": ["black", "isort", "flake8", "ruff"],
        "mcp-http": ["fastapi>=0.110.0", "uvicorn[standard]>=0.22.0"],
        "full": [
            "sentence-transformers>=2.2.0",
            "openai>=0.27.0",
            "faiss-cpu>=1.7.4",
            "keybert>=0.7.0",
            "scikit-learn>=1.3.0",
            "transformers>=4.40.0",
            "spacy>=3.5.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "greeum=greeum.cli:main",
        ],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Operating System :: OS Independent",
    ],
)
