# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from seerep.pb import boundingbox_pb2 as boundingbox__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from seerep.pb import projectCreation_pb2 as projectCreation__pb2
from seerep.pb import project_info_pb2 as project__info__pb2
from seerep.pb import project_infos_pb2 as project__infos__pb2
from seerep.pb import string_vector_pb2 as string__vector__pb2
from seerep.pb import time_interval_pb2 as time__interval__pb2
from seerep.pb import uuid_datatype_pair_pb2 as uuid__datatype__pair__pb2
from seerep.pb import uuid_datatype_with_category_pb2 as uuid__datatype__with__category__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in meta_operations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetaOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProject = channel.unary_unary(
                '/seerep.pb.MetaOperations/CreateProject',
                request_serializer=projectCreation__pb2.ProjectCreation.SerializeToString,
                response_deserializer=project__info__pb2.ProjectInfo.FromString,
                _registered_method=True)
        self.GetProjects = channel.unary_unary(
                '/seerep.pb.MetaOperations/GetProjects',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=project__infos__pb2.ProjectInfos.FromString,
                _registered_method=True)
        self.GetOverallTimeInterval = channel.unary_unary(
                '/seerep.pb.MetaOperations/GetOverallTimeInterval',
                request_serializer=uuid__datatype__pair__pb2.UuidDatatypePair.SerializeToString,
                response_deserializer=time__interval__pb2.TimeInterval.FromString,
                _registered_method=True)
        self.GetOverallBoundingBox = channel.unary_unary(
                '/seerep.pb.MetaOperations/GetOverallBoundingBox',
                request_serializer=uuid__datatype__pair__pb2.UuidDatatypePair.SerializeToString,
                response_deserializer=boundingbox__pb2.Boundingbox.FromString,
                _registered_method=True)
        self.GetAllCategories = channel.unary_unary(
                '/seerep.pb.MetaOperations/GetAllCategories',
                request_serializer=uuid__datatype__pair__pb2.UuidDatatypePair.SerializeToString,
                response_deserializer=string__vector__pb2.StringVector.FromString,
                _registered_method=True)
        self.GetAllLabels = channel.unary_unary(
                '/seerep.pb.MetaOperations/GetAllLabels',
                request_serializer=uuid__datatype__with__category__pb2.UuidDatatypeWithCategory.SerializeToString,
                response_deserializer=string__vector__pb2.StringVector.FromString,
                _registered_method=True)


class MetaOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverallTimeInterval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverallBoundingBox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllLabels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetaOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=projectCreation__pb2.ProjectCreation.FromString,
                    response_serializer=project__info__pb2.ProjectInfo.SerializeToString,
            ),
            'GetProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjects,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=project__infos__pb2.ProjectInfos.SerializeToString,
            ),
            'GetOverallTimeInterval': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverallTimeInterval,
                    request_deserializer=uuid__datatype__pair__pb2.UuidDatatypePair.FromString,
                    response_serializer=time__interval__pb2.TimeInterval.SerializeToString,
            ),
            'GetOverallBoundingBox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverallBoundingBox,
                    request_deserializer=uuid__datatype__pair__pb2.UuidDatatypePair.FromString,
                    response_serializer=boundingbox__pb2.Boundingbox.SerializeToString,
            ),
            'GetAllCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCategories,
                    request_deserializer=uuid__datatype__pair__pb2.UuidDatatypePair.FromString,
                    response_serializer=string__vector__pb2.StringVector.SerializeToString,
            ),
            'GetAllLabels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllLabels,
                    request_deserializer=uuid__datatype__with__category__pb2.UuidDatatypeWithCategory.FromString,
                    response_serializer=string__vector__pb2.StringVector.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seerep.pb.MetaOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seerep.pb.MetaOperations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetaOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seerep.pb.MetaOperations/CreateProject',
            projectCreation__pb2.ProjectCreation.SerializeToString,
            project__info__pb2.ProjectInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seerep.pb.MetaOperations/GetProjects',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            project__infos__pb2.ProjectInfos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverallTimeInterval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seerep.pb.MetaOperations/GetOverallTimeInterval',
            uuid__datatype__pair__pb2.UuidDatatypePair.SerializeToString,
            time__interval__pb2.TimeInterval.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverallBoundingBox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seerep.pb.MetaOperations/GetOverallBoundingBox',
            uuid__datatype__pair__pb2.UuidDatatypePair.SerializeToString,
            boundingbox__pb2.Boundingbox.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seerep.pb.MetaOperations/GetAllCategories',
            uuid__datatype__pair__pb2.UuidDatatypePair.SerializeToString,
            string__vector__pb2.StringVector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllLabels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seerep.pb.MetaOperations/GetAllLabels',
            uuid__datatype__with__category__pb2.UuidDatatypeWithCategory.SerializeToString,
            string__vector__pb2.StringVector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
