import secrets


# Simple lists of adjectives and nouns for meaningful thread names

ADJECTIVES = [
    "brave",
    "curious",
    "gentle",
    "clever",
    "bright",
    "silent",
    "quick",
    "calm",
    "bold",
    "wise",
    "cheerful",
    "eager",
    "friendly",
    "keen",
    "lively",
    "mighty",
    "noble",
    "proud",
    "serene",
    "vivid",
    "dynamic",
    "creative",
    "thoughtful",
    "playful",
    "optimistic",
    "resourceful",
    "inventive",
    "patient",
    "resolute",
    "spirited",
    "fearless",
    "graceful",
    "humble",
    "imaginative",
    "jovial",
    "meticulous",
    "persistent",
    "radiant",
    "sincere",
    "tenacious",
    "uplifting",
    "versatile",
    "witty",
    "zealous",
    "adaptable",
    "diligent",
    "enthusiastic",
    "forgiving",
    "generous",
    "harmonious",
]
NOUNS = [
    "explorer",
    "journey",
    "summit",
    "horizon",
    "dialogue",
    "insight",
    "venture",
    "quest",
    "haven",
    "spark",
    "companion",
    "discovery",
    "exchange",
    "path",
    "vision",
    "story",
    "thread",
    "domain",
    "focus",
    "adventure",
    "beacon",
    "cascade",
    "dream",
    "echo",
    "flame",
    "garden",
    "harbor",
    "idea",
    "junction",
    "keystone",
    "landmark",
    "momentum",
    "notion",
    "odyssey",
    "paradigm",
    "quest",
    "refuge",
    "sanctuary",
    "trail",
    "universe",
    "venture",
    "whisper",
    "zenith",
    "alliance",
    "bridge",
    "canvas",
    "dialogue",
    "enclave",
    "forum",
]


def generate_dummy_thread_name(separator: str = " ") -> str:
    """
    Generate a meaningful English name for an AI chat thread.
    Example: 'curious-explorer', 'gentle-dialogue', etc.
    """
    adj = ADJECTIVES[secrets.randbelow(len(ADJECTIVES))]
    noun = NOUNS[secrets.randbelow(len(NOUNS))]
    return f"{adj}{separator}{noun}"
