# Generated by Django 4.2.23 on 2025-08-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AppleDevice',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('push_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApplePassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='pretix_uic_barcode.appledevice')),
                ('order_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_registrations', to='pretixbase.orderposition')),
            ],
            options={
                'unique_together': {('order_position', 'device')},
            },
        ),
        migrations.CreateModel(
            name='AppleWalletPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pass_type_id', models.CharField(max_length=255)),
                ('pass_serial', models.CharField(max_length=255)),
                ('contents_hash', models.BinaryField()),
                ('last_modified', models.DateTimeField()),
                ('order_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apple_wallet_pass', to='pretixbase.orderposition')),
            ],
            options={
                'unique_together': {('pass_type_id', 'pass_serial')},
                'index_together': {('pass_type_id', 'pass_serial')},
            },
        ),
    ]
