# Generated by Django 4.2.23 on 2025-08-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_uic_barcode', '0004_orderpositiontotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timestamp',),
                'unique_together': {('class_id', 'object_id', 'nonce')},
            },
        ),
    ]
