
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-17T10:41:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f66b7bcb2d7fb83973c9034f6d47c26f7bdb9e78",
 "version": "v1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
