import pytest
from . import settings as settings
from .file import YamlFile as YamlFile
from .templates import add_globals as add_globals
from _typeshed import Incomplete
from pathlib import Path

logger: Incomplete

def pytest_addhooks(pluginmanager) -> None: ...
def pytest_addoption(parser) -> None: ...
def pytest_configure(config: pytest.Config): ...
def pytest_collect_file(parent, file_path: Path): ...
