# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Boundingbox(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Boundingbox()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBoundingbox(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Boundingbox
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Boundingbox
    def CenterPoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from seerep.fb.Point import Point
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Boundingbox
    def SpatialExtent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from seerep.fb.Point import Point
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Boundingbox
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from seerep.fb.Quaternion import Quaternion
            obj = Quaternion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(3)
def BoundingboxStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddCenterPoint(builder, centerPoint): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(centerPoint), 0)
def BoundingboxAddCenterPoint(builder, centerPoint):
    """This method is deprecated. Please switch to AddCenterPoint."""
    return AddCenterPoint(builder, centerPoint)
def AddSpatialExtent(builder, spatialExtent): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spatialExtent), 0)
def BoundingboxAddSpatialExtent(builder, spatialExtent):
    """This method is deprecated. Please switch to AddSpatialExtent."""
    return AddSpatialExtent(builder, spatialExtent)
def AddRotation(builder, rotation): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(rotation), 0)
def BoundingboxAddRotation(builder, rotation):
    """This method is deprecated. Please switch to AddRotation."""
    return AddRotation(builder, rotation)
def End(builder): return builder.EndObject()
def BoundingboxEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)