# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Label(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Label()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLabel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Label
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Label
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Label
    def LabelIdDatumaro(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Label
    def InstanceUuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Label
    def InstanceIdDatumaro(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(4)
def LabelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddLabel(builder, label): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)
def LabelAddLabel(builder, label):
    """This method is deprecated. Please switch to AddLabel."""
    return AddLabel(builder, label)
def AddLabelIdDatumaro(builder, labelIdDatumaro): builder.PrependInt32Slot(1, labelIdDatumaro, 0)
def LabelAddLabelIdDatumaro(builder, labelIdDatumaro):
    """This method is deprecated. Please switch to AddLabelIdDatumaro."""
    return AddLabelIdDatumaro(builder, labelIdDatumaro)
def AddInstanceUuid(builder, instanceUuid): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(instanceUuid), 0)
def LabelAddInstanceUuid(builder, instanceUuid):
    """This method is deprecated. Please switch to AddInstanceUuid."""
    return AddInstanceUuid(builder, instanceUuid)
def AddInstanceIdDatumaro(builder, instanceIdDatumaro): builder.PrependInt32Slot(3, instanceIdDatumaro, 0)
def LabelAddInstanceIdDatumaro(builder, instanceIdDatumaro):
    """This method is deprecated. Please switch to AddInstanceIdDatumaro."""
    return AddInstanceIdDatumaro(builder, instanceIdDatumaro)
def End(builder): return builder.EndObject()
def LabelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)