# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProjectInfos(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProjectInfos()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProjectInfos(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProjectInfos
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProjectInfos
    def Projects(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from seerep.fb.ProjectInfo import ProjectInfo
            obj = ProjectInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ProjectInfos
    def ProjectsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProjectInfos
    def ProjectsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def ProjectInfosStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddProjects(builder, projects): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(projects), 0)
def ProjectInfosAddProjects(builder, projects):
    """This method is deprecated. Please switch to AddProjects."""
    return AddProjects(builder, projects)
def StartProjectsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ProjectInfosStartProjectsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartProjectsVector(builder, numElems)
def End(builder): return builder.EndObject()
def ProjectInfosEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)