# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QueryInstance(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QueryInstance()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQueryInstance(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QueryInstance
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QueryInstance
    def Datatype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # QueryInstance
    def Query(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from seerep.fb.Query import Query
            obj = Query()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def QueryInstanceStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddDatatype(builder, datatype): builder.PrependInt8Slot(0, datatype, 0)
def QueryInstanceAddDatatype(builder, datatype):
    """This method is deprecated. Please switch to AddDatatype."""
    return AddDatatype(builder, datatype)
def AddQuery(builder, query): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(query), 0)
def QueryInstanceAddQuery(builder, query):
    """This method is deprecated. Please switch to AddQuery."""
    return AddQuery(builder, query)
def End(builder): return builder.EndObject()
def QueryInstanceEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)