
# This file was generated by 'versioneer.py' (0.29+8.gf9bbd1b) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-17T01:39:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6401751304a777605cf19bf60cb71000b976cfa",
 "version": "0.71.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
