from metasequoia_java.sa.utils.name_utils import get_first_name_from_absolute_name
from metasequoia_java.sa.utils.name_utils import get_last_name_from_absolute_name
from metasequoia_java.sa.utils.name_utils import split_last_name_from_absolute_name
from metasequoia_java.sa.utils.node_utils import is_long_member_select
