# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/hyphae/api/api.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'truffle/hyphae/api/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from truffle.infer import irequest_pb2 as truffle_dot_infer_dot_irequest__pb2
from truffle.common import app_tool_pb2 as truffle_dot_common_dot_app__tool__pb2
from truffle.hyphae import contextmgmt_pb2 as truffle_dot_hyphae_dot_contextmgmt__pb2
from truffle.hyphae.api import globalvars_pb2 as truffle_dot_hyphae_dot_api_dot_globalvars__pb2
from truffle.hyphae.api import urr_pb2 as truffle_dot_hyphae_dot_api_dot_urr__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctruffle/hyphae/api/api.proto\x12\x12truffle.hyphae.api\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1ctruffle/infer/irequest.proto\x1a\x1dtruffle/common/app_tool.proto\x1a truffle/hyphae/contextmgmt.proto\x1a#truffle/hyphae/api/globalvars.proto\x1a\x1ctruffle/hyphae/api/urr.proto2h\n\tHyphaeAPI\x12[\n\nGlobalVars\x12%.truffle.hyphae.api.GlobalVarsRequest\x1a&.truffle.hyphae.api.GlobalVarsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.hyphae.api.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HYPHAEAPI']._serialized_start=243
  _globals['_HYPHAEAPI']._serialized_end=347
# @@protoc_insertion_point(module_scope)
