"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import sys
import typing

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Node(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_FIELD_NUMBER: builtins.int
    IS_LEAF_FIELD_NUMBER: builtins.int
    KEYS_FIELD_NUMBER: builtins.int
    CHILDREN_IDS_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    NEXT_ID_FIELD_NUMBER: builtins.int
    PREV_ID_FIELD_NUMBER: builtins.int
    order: builtins.int
    is_leaf: builtins.bool
    @property
    def keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def children_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    next_id: builtins.str
    prev_id: builtins.str
    def __init__(
        self,
        *,
        order: builtins.int = ...,
        is_leaf: builtins.bool = ...,
        keys: collections.abc.Iterable[builtins.str] | None = ...,
        children_ids: collections.abc.Iterable[builtins.str] | None = ...,
        values: collections.abc.Iterable[builtins.bytes] | None = ...,
        next_id: builtins.str = ...,
        prev_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["children_ids", b"children_ids", "is_leaf", b"is_leaf", "keys", b"keys", "next_id", b"next_id", "order", b"order", "prev_id", b"prev_id", "values", b"values"]) -> None: ...

global___Node = Node

@typing_extensions.final
class NodeCreateRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_FIELD_NUMBER: builtins.int
    IS_LEAF_FIELD_NUMBER: builtins.int
    KEYS_FIELD_NUMBER: builtins.int
    CHILDREN_IDS_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    NEXT_ID_FIELD_NUMBER: builtins.int
    PREV_ID_FIELD_NUMBER: builtins.int
    order: builtins.int
    is_leaf: builtins.bool
    @property
    def keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def children_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    next_id: builtins.str
    prev_id: builtins.str
    def __init__(
        self,
        *,
        order: builtins.int = ...,
        is_leaf: builtins.bool = ...,
        keys: collections.abc.Iterable[builtins.str] | None = ...,
        children_ids: collections.abc.Iterable[builtins.str] | None = ...,
        values: collections.abc.Iterable[builtins.bytes] | None = ...,
        next_id: builtins.str = ...,
        prev_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["children_ids", b"children_ids", "is_leaf", b"is_leaf", "keys", b"keys", "next_id", b"next_id", "order", b"order", "prev_id", b"prev_id", "values", b"values"]) -> None: ...

global___NodeCreateRequest = NodeCreateRequest

@typing_extensions.final
class NodeCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___NodeCreateResponse = NodeCreateResponse

@typing_extensions.final
class NodeSearchRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    key: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key"]) -> None: ...

global___NodeSearchRequest = NodeSearchRequest

@typing_extensions.final
class NodeSearchResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    found: builtins.bool
    value: builtins.bytes
    """NOTE: this is a message of type `Value`, but for performance
    reasons we don't bother deserializing it except when a user is
    calling into the `Index` type directly.
    """
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        value: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_value", b"_value", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_value", b"_value", "found", b"found", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_value", b"_value"]) -> typing_extensions.Literal["value"] | None: ...

global___NodeSearchResponse = NodeSearchResponse

@typing_extensions.final
class NodeInsertRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.bytes
    """NOTE: this is a message of type `Value`, but for performance
    reasons we don't bother deserializing it except when a user is
    calling into the `Index` type directly.
    """
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

global___NodeInsertRequest = NodeInsertRequest

@typing_extensions.final
class NodeInsertResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPLIT_FIELD_NUMBER: builtins.int
    PROMOTED_KEY_FIELD_NUMBER: builtins.int
    NEW_CHILD_ID_FIELD_NUMBER: builtins.int
    split: builtins.bool
    promoted_key: builtins.str
    new_child_id: builtins.str
    def __init__(
        self,
        *,
        split: builtins.bool = ...,
        promoted_key: builtins.str = ...,
        new_child_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["new_child_id", b"new_child_id", "promoted_key", b"promoted_key", "split", b"split"]) -> None: ...

global___NodeInsertResponse = NodeInsertResponse

@typing_extensions.final
class NodeRemoveRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    key: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key"]) -> None: ...

global___NodeRemoveRequest = NodeRemoveRequest

@typing_extensions.final
class NodeRemoveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___NodeRemoveResponse = NodeRemoveResponse

@typing_extensions.final
class NodeRangeRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_KEY_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    start_key: builtins.str
    """The start key to scan from (inclusive). If not specified,
    the range is unbounded at the start.
    """
    limit: builtins.int
    """The maximum number of entries to return. Must be specified and
    non-zero.
    """
    def __init__(
        self,
        *,
        start_key: builtins.str | None = ...,
        limit: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_start_key", b"_start_key", "start_key", b"start_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_start_key", b"_start_key", "limit", b"limit", "start_key", b"start_key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_start_key", b"_start_key"]) -> typing_extensions.Literal["start_key"] | None: ...

global___NodeRangeRequest = NodeRangeRequest

@typing_extensions.final
class NodeRangeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NodeEntry]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___NodeEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___NodeRangeResponse = NodeRangeResponse

@typing_extensions.final
class NodeReverseRangeRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_KEY_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    start_key: builtins.str
    """The start key to scan from (inclusive). If not specified,
    the range is unbounded at the start.
    """
    limit: builtins.int
    """The maximum number of entries to return. Must be specified and
    non-zero.
    """
    def __init__(
        self,
        *,
        start_key: builtins.str | None = ...,
        limit: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_start_key", b"_start_key", "start_key", b"start_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_start_key", b"_start_key", "limit", b"limit", "start_key", b"start_key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_start_key", b"_start_key"]) -> typing_extensions.Literal["start_key"] | None: ...

global___NodeReverseRangeRequest = NodeReverseRangeRequest

@typing_extensions.final
class NodeReverseRangeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NodeEntry]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___NodeEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___NodeReverseRangeResponse = NodeReverseRangeResponse

@typing_extensions.final
class NodeStringifyRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEVEL_FIELD_NUMBER: builtins.int
    level: builtins.int
    def __init__(
        self,
        *,
        level: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["level", b"level"]) -> None: ...

global___NodeStringifyRequest = NodeStringifyRequest

@typing_extensions.final
class NodeStringifyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.str
    def __init__(
        self,
        *,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["value", b"value"]) -> None: ...

global___NodeStringifyResponse = NodeStringifyResponse

@typing_extensions.final
class NodeEntry(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////

    See `Range` and `ReverseRange`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.bytes
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

global___NodeEntry = NodeEntry

@typing_extensions.final
class InvalidRangeError(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////

    See `Range` and `ReverseRange`. Raised when the requested range
    is not valid.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message"]) -> None: ...

global___InvalidRangeError = InvalidRangeError

@typing_extensions.final
class Index(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_FIELD_NUMBER: builtins.int
    ROOT_ID_FIELD_NUMBER: builtins.int
    order: builtins.int
    root_id: builtins.str
    def __init__(
        self,
        *,
        order: builtins.int = ...,
        root_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["order", b"order", "root_id", b"root_id"]) -> None: ...

global___Index = Index

@typing_extensions.final
class IndexCreateRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_FIELD_NUMBER: builtins.int
    order: builtins.int
    def __init__(
        self,
        *,
        order: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["order", b"order"]) -> None: ...

global___IndexCreateRequest = IndexCreateRequest

@typing_extensions.final
class IndexCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IndexCreateResponse = IndexCreateResponse

@typing_extensions.final
class IndexSearchRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    key: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key"]) -> None: ...

global___IndexSearchRequest = IndexSearchRequest

@typing_extensions.final
class IndexSearchResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    ANY_FIELD_NUMBER: builtins.int
    found: builtins.bool
    @property
    def value(self) -> google.protobuf.struct_pb2.Value:
        """NOTE: see comment in `IndexInsertRequest` for why we have
        multiple "value" fields.
        """
    bytes: builtins.bytes
    @property
    def any(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        value: google.protobuf.struct_pb2.Value | None = ...,
        bytes: builtins.bytes | None = ...,
        any: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_any", b"_any", "_bytes", b"_bytes", "_value", b"_value", "any", b"any", "bytes", b"bytes", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_any", b"_any", "_bytes", b"_bytes", "_value", b"_value", "any", b"any", "bytes", b"bytes", "found", b"found", "value", b"value"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_any", b"_any"]) -> typing_extensions.Literal["any"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_bytes", b"_bytes"]) -> typing_extensions.Literal["bytes"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_value", b"_value"]) -> typing_extensions.Literal["value"] | None: ...

global___IndexSearchResponse = IndexSearchResponse

@typing_extensions.final
class IndexInsertRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    ANY_FIELD_NUMBER: builtins.int
    key: builtins.str
    @property
    def value(self) -> google.protobuf.struct_pb2.Value:
        """NOTE: we provide many "value" fields to provide a better
        developer experience when storing different types. For example,
        in TypeScript you will probably only ever use `value` and maybe
        `bytes`, but in Python `any` may be more useful when using
        protobuf directly.

        We're not using a `oneof` because the code generation of those
        are all different and not always more clear what the intent is,
        see this blog post which illuminates this in more detail, and may
        also be a better way of doing validation then the manual
        validation that we're doing in the servicer:
        https://buf.build/blog/fixing-oneofs

        TODO: consider also having `string_value`, `number_value`, etc,
        to provide a better developer experience in languages other than
        TypeScript which has first-class support for passing JSON
        stringifiable objects to `value`.
        """
    bytes: builtins.bytes
    @property
    def any(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: google.protobuf.struct_pb2.Value | None = ...,
        bytes: builtins.bytes | None = ...,
        any: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_any", b"_any", "_bytes", b"_bytes", "_value", b"_value", "any", b"any", "bytes", b"bytes", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_any", b"_any", "_bytes", b"_bytes", "_value", b"_value", "any", b"any", "bytes", b"bytes", "key", b"key", "value", b"value"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_any", b"_any"]) -> typing_extensions.Literal["any"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_bytes", b"_bytes"]) -> typing_extensions.Literal["bytes"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_value", b"_value"]) -> typing_extensions.Literal["value"] | None: ...

global___IndexInsertRequest = IndexInsertRequest

@typing_extensions.final
class IndexInsertResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IndexInsertResponse = IndexInsertResponse

@typing_extensions.final
class IndexRemoveRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    key: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key"]) -> None: ...

global___IndexRemoveRequest = IndexRemoveRequest

@typing_extensions.final
class IndexRemoveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IndexRemoveResponse = IndexRemoveResponse

@typing_extensions.final
class IndexRangeRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_KEY_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    start_key: builtins.str
    """The start key to scan from (inclusive). If not specified,
    the range is unbounded at the start.
    """
    limit: builtins.int
    """The maximum number of entries to return. Must be specified and
    non-zero.
    """
    def __init__(
        self,
        *,
        start_key: builtins.str | None = ...,
        limit: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_start_key", b"_start_key", "start_key", b"start_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_start_key", b"_start_key", "limit", b"limit", "start_key", b"start_key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_start_key", b"_start_key"]) -> typing_extensions.Literal["start_key"] | None: ...

global___IndexRangeRequest = IndexRangeRequest

@typing_extensions.final
class IndexRangeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Entry]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___Entry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___IndexRangeResponse = IndexRangeResponse

@typing_extensions.final
class IndexReverseRangeRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_KEY_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    start_key: builtins.str
    """The start key to scan from (inclusive). If not specified,
    the range is unbounded at the start.
    """
    limit: builtins.int
    """The maximum number of entries to return. Must be specified and
    non-zero.
    """
    def __init__(
        self,
        *,
        start_key: builtins.str | None = ...,
        limit: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_start_key", b"_start_key", "start_key", b"start_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_start_key", b"_start_key", "limit", b"limit", "start_key", b"start_key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_start_key", b"_start_key"]) -> typing_extensions.Literal["start_key"] | None: ...

global___IndexReverseRangeRequest = IndexReverseRangeRequest

@typing_extensions.final
class IndexReverseRangeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Entry]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___Entry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___IndexReverseRangeResponse = IndexReverseRangeResponse

@typing_extensions.final
class IndexStringifyRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IndexStringifyRequest = IndexStringifyRequest

@typing_extensions.final
class IndexStringifyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.str
    def __init__(
        self,
        *,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["value", b"value"]) -> None: ...

global___IndexStringifyResponse = IndexStringifyResponse

@typing_extensions.final
class Entry(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////

    See `Range` and `ReverseRange`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    ANY_FIELD_NUMBER: builtins.int
    key: builtins.str
    @property
    def value(self) -> google.protobuf.struct_pb2.Value: ...
    bytes: builtins.bytes
    @property
    def any(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: google.protobuf.struct_pb2.Value | None = ...,
        bytes: builtins.bytes | None = ...,
        any: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_any", b"_any", "_bytes", b"_bytes", "_value", b"_value", "any", b"any", "bytes", b"bytes", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_any", b"_any", "_bytes", b"_bytes", "_value", b"_value", "any", b"any", "bytes", b"bytes", "key", b"key", "value", b"value"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_any", b"_any"]) -> typing_extensions.Literal["any"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_bytes", b"_bytes"]) -> typing_extensions.Literal["bytes"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_value", b"_value"]) -> typing_extensions.Literal["value"] | None: ...

global___Entry = Entry

@typing_extensions.final
class Value(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    ANY_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> google.protobuf.struct_pb2.Value: ...
    bytes: builtins.bytes
    @property
    def any(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        value: google.protobuf.struct_pb2.Value | None = ...,
        bytes: builtins.bytes = ...,
        any: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["any", b"any", "bytes", b"bytes", "options", b"options", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["any", b"any", "bytes", b"bytes", "options", b"options", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["options", b"options"]) -> typing_extensions.Literal["value", "bytes", "any"] | None: ...

global___Value = Value
