from enum import Enum

class PermissionsRegistry:
    def __init__(self) -> None: ...
    def register_permission(self, name: str, value: str | None = ...) -> None: ...
    def register_permissions(self, permissions: dict[str, str | None]) -> None: ...
    def get_permissions_registry(self) -> dict[str, str]: ...
    def get_all_permission_values(self) -> set[str]: ...
    def get_permission_by_name(self, name: str) -> str | None: ...
    def build_permissions_enum(self) -> Enum: ...
