"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from compass_api_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class UnsignedTransactionTypedDict(TypedDict):
    chain_id: str
    r"""The chain id of the transaction"""
    data: str
    r"""The data of the transaction"""
    from_: str
    r"""The sender of the transaction"""
    gas: str
    r"""The gas of the transaction"""
    to: str
    r"""The recipient of the transaction"""
    value: str
    r"""The value of the transaction"""
    nonce: str
    r"""The nonce of the address"""
    max_fee_per_gas: str
    r"""The max fee per gas of the transaction"""
    max_priority_fee_per_gas: str
    r"""The max priority fee per gas of the transaction"""


class UnsignedTransaction(BaseModel):
    chain_id: Annotated[str, pydantic.Field(alias="chainId")]
    r"""The chain id of the transaction"""

    data: str
    r"""The data of the transaction"""

    from_: Annotated[str, pydantic.Field(alias="from")]
    r"""The sender of the transaction"""

    gas: str
    r"""The gas of the transaction"""

    to: str
    r"""The recipient of the transaction"""

    value: str
    r"""The value of the transaction"""

    nonce: str
    r"""The nonce of the address"""

    max_fee_per_gas: Annotated[str, pydantic.Field(alias="maxFeePerGas")]
    r"""The max fee per gas of the transaction"""

    max_priority_fee_per_gas: Annotated[
        str, pydantic.Field(alias="maxPriorityFeePerGas")
    ]
    r"""The max priority fee per gas of the transaction"""
