"""Type stubs for machine_dialect_vm module."""

from typing import Any

__version__: str

class RustVM:
    """Rust VM for executing Machine Dialect™ bytecode."""

    def __init__(self) -> None: ...
    def set_debug(self, enabled: bool) -> None: ...
    def instruction_count(self) -> int: ...
    def load_bytecode(self, path: str) -> None: ...
    def execute(self) -> Any: ...
    def reset(self) -> None: ...
