{
 "title": "Treasury Balances",
 "description": "Displays real-time balances of the DAO's treasury assets, including YFI, ETH, BTC, \"cash\" (stablecoins), and other assets, as well as liabilities and debt. Useful for monitoring the DAO's current financial position and asset allocation.",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "YFI in Treasury",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"balance\",token=\"YFI\"})",
     "legendFormat": "YFI Balance"
    },
    {
     "expr": "sum(treasury_assets{param=\"usd value\",token=\"YFI\"})",
     "legendFormat": "YFI Value"
    },
    {
     "expr": "sum(treasury_assets{param=\"usd value\",token=\"yvYFI\"})",
     "legendFormat": "yvYFI Value"
    }
   ]
  },
  {
   "title": "YFI in Treasury ($)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",token=\"YFI\"}) + sum(treasury_assets{param=\"usd value\",token=\"yvYFI\"})"
    }
   ]
  },
  {
   "title": "Liquid Assets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket!=\"YFI\", bucket!=\"Other long term assets\"})"
    }
   ]
  },
  {
   "title": "ETH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"ETH\"})"
    }
   ]
  },
  {
   "title": "BTC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"BTC\"})"
    }
   ]
  },
  {
   "title": "Cash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\", bucket=\"Cash & cash equivalents\"})"
    }
   ]
  },
  {
   "title": "Treasury Debt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_debt{param=\"usd value\"})"
    }
   ]
  },
  {
   "title": "Cash - Debt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Cash & cash equivalents\"}) - sum(treasury_debt{param=\"usd value\"})"
    }
   ]
  },
  {
   "title": "Liquid Assets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket!=\"YFI\", bucket!=\"Other long term assets\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Protocol Debt",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(treasury_debt{param=\"usd value\"}) by (token)",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Assets - Debt",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket!=\"YFI\",bucket!=\"Other long term assets\"})",
     "legendFormat": "Liquid Assets"
    },
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Cash & cash equivalents\"})",
     "legendFormat": "Cash"
    },
    {
     "expr": "sum(treasury_debt{param=\"usd value\"})",
     "legendFormat": "Debt"
    },
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Cash & cash equivalents\"}) - sum(treasury_debt{param=\"usd value\"})",
     "legendFormat": "Cash - Debt"
    },
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket!=\"YFI\"}) - sum(treasury_debt{param=\"usd value\"})",
     "legendFormat": "Liquid Assets - Debt"
    }
   ]
  },
  {
   "title": "Debt to Asset Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(treasury_debt{param=\"usd value\"})"
    },
    {
     "expr": "sum(treasury_assets{param=\"usd value\",bucket!=\"Other long term assets\"})"
    }
   ]
  },
  {
   "title": "Liquid Cash",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Liquid Cash",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Cash & cash equivalents\"}) by (token)",
       "legendFormat": "{{token}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Liquid ETH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Liquid ETH",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"ETH\"}) by (token)",
       "legendFormat": "{{token}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Liquid BTC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Liquid BTC",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"BTC\"}) by (token)",
       "legendFormat": "{{token}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Liquid Everything Else",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Liquid Everything Else",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Other short term assets\"}) by (token)",
       "legendFormat": "{{token}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Liquid Cash by Wallet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Liquid Cash by Wallet",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Cash & cash equivalents\"}) by (token,wallet)",
       "legendFormat": "{{token}} | {{wallet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Liquid ETH by Wallet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Liquid ETH by Wallet",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"ETH\"}) by (token,wallet)",
       "legendFormat": "{{token}} | {{wallet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Liquid BTC by Wallet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Liquid BTC by Wallet",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"BTC\"}) by (token, wallet)",
       "legendFormat": "{{token}} | {{wallet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Liquid Everything Else by Wallet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Liquid Everything Else by Wallet",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum(treasury_assets{param=\"usd value\",bucket=\"Other short term assets\"}) by (token, wallet)",
       "legendFormat": "{{token}} | {{wallet}}"
      }
     ]
    }
   ]
  }
 ]
}