# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/common/app_tool.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'truffle/common/app_tool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truffle.common import icon_pb2 as truffle_dot_common_dot_icon__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtruffle/common/app_tool.proto\x12\x0etruffle.common\x1a\x19truffle/common/icon.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8d\x05\n\x07\x41ppTool\x12\x19\n\x11tool_display_name\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x18\n\x10tool_description\x18\x03 \x01(\t\x12\x38\n\ttool_args\x18\x04 \x03(\x0b\x32%.truffle.common.AppTool.ToolArgsEntry\x12\'\n\ttool_icon\x18\x05 \x01(\x0b\x32\x14.truffle.common.Icon\x12:\n\x0btool_origin\x18\x06 \x01(\x0e\x32%.truffle.common.AppTool.AppToolOrigin\x12\x36\n\ttool_type\x18\x07 \x01(\x0e\x32#.truffle.common.AppTool.AppToolType\x12+\n\ntool_flags\x18\x08 \x01(\x0b\x32\x17.google.protobuf.Struct\x1a/\n\rToolArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa1\x01\n\rAppToolOrigin\x12\x1f\n\x1b\x41PP_TOOL_ORIGIN_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x41PP_TOOL_ORIGIN_SYSTEM\x10\x01\x12\x18\n\x14\x41PP_TOOL_ORIGIN_USER\x10\x02\x12\x1c\n\x18\x41PP_TOOL_ORIGIN_OVERRIDE\x10\x03\x12\x1b\n\x17\x41PP_TOOL_ORIGIN_RUNTIME\x10\x04\"a\n\x0b\x41ppToolType\x12\x1d\n\x19\x41PP_TOOL_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x41PP_TOOL_TYPE_STANDARD\x10\x01\x12\x17\n\x13\x41PP_TOOL_TYPE_ASYNC\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.common.app_tool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPTOOL_TOOLARGSENTRY']._loaded_options = None
  _globals['_APPTOOL_TOOLARGSENTRY']._serialized_options = b'8\001'
  _globals['_APPTOOL']._serialized_start=107
  _globals['_APPTOOL']._serialized_end=760
  _globals['_APPTOOL_TOOLARGSENTRY']._serialized_start=450
  _globals['_APPTOOL_TOOLARGSENTRY']._serialized_end=497
  _globals['_APPTOOL_APPTOOLORIGIN']._serialized_start=500
  _globals['_APPTOOL_APPTOOLORIGIN']._serialized_end=661
  _globals['_APPTOOL_APPTOOLTYPE']._serialized_start=663
  _globals['_APPTOOL_APPTOOLTYPE']._serialized_end=760
# @@protoc_insertion_point(module_scope)
