__title__ = "cpymad-lhc"
__description__ = "Helper functions to run LHC optics in cpymad"
__url__ = "https://github.com/JoschD/cpymad_lhc"
__version__ = "0.2.1"
__author__ = "JoschD"
__author_email__ = "JoschD@github.com"
__license__ = "MIT"