from .qt import QApplication as QApplication, QCursor as QCursor, QRect as QRect, QScreen as QScreen
from _typeshed import Incomplete

def currentScreen() -> QScreen | None: ...
def currentScreenGeometry(availableGeometry: bool = True) -> QRect: ...

class singledispatchmethod:
    dispatcher: Incomplete
    func: Incomplete
    def __init__(self, func) -> None: ...
    def register(self, cls, method=None): ...
    def __get__(self, obj, cls=None): ...
    @property
    def __isabstractmethod__(self): ...
