from typing import Any

def TET_new() -> int: ...
def TET_set_option(t: int, optlist: str) -> None: ...
def TET_delete(t: int) -> None: ...
def TET_close_document(t: int, doc: int) -> None: ...
def TET_close_page(t: int, page: int) -> None: ...
def TET_convert_to_unicode(
    t: int, inputformat: str, inputstring: str, optlist: str
) -> str: ...
def TET_create_pvf(t: int, filename: str, data: Any, optlist: str) -> None: ...
def TET_delete_pvf(t: int, filename: str) -> int: ...
def TET_get_apiname(t: int) -> str: ...
def TET_get_char_info(t: int, page: int) -> str: ...
def TET_get_color_info(t: int, doc: int, colorid: int, optlist: str) -> str: ...
def TET_get_errmsg(t: int) -> str: ...
def TET_get_errnum(t: int) -> int: ...
def TET_get_image_data(t: int, doc: int, imageid: int, optlist: str) -> str: ...
def TET_get_image_info(t: int, page: int) -> str: ...
def TET_get_text(t: int, page: int) -> str: ...
def TET_info_pvf(t: int, filename: str, keyword: str) -> str: ...
def TET_open_document(t: int, filename: str, optlist: str) -> int: ...
def TET_open_page(t: int, doc: int, pagenumber: int, optlist: str) -> int: ...
def TET_pcos_get_number(t: int, doc: int, path: str) -> float: ...
def TET_pcos_get_string(t: int, doc: int, path: str) -> str: ...
def TET_pcos_get_stream(t: int, doc: int, optlist: str, path: str) -> Any: ...
def TET_write_image_file(t: int, doc: int, imageid: int, optlist: str) -> int: ...
def TET_process_page(p: int, doc: int, pageno: int, optlist: str) -> int: ...
def TET_get_tetml(p: int, doc: int, optlist: str) -> str: ...
