# Generated by ariadne-codegen
# Source: codegen/ebo/queries

from typing import Any, Dict, Optional

from .base_client import BaseClient
from .current_epoch import CurrentEpoch, CurrentEpochNetwork


def gql(q: str) -> str:
    return q


class EBOClient(BaseClient):
    def current_epoch(
        self, network_id: str, **kwargs: Any
    ) -> Optional[CurrentEpochNetwork]:
        query = gql(
            """
            query CurrentEpoch($network_id: ID!) {
              network(id: $network_id) {
                latestValidBlockNumber {
                  network {
                    id
                  }
                  epochNumber
                  blockNumber
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"network_id": network_id}
        response = self.execute(
            query=query, operation_name="CurrentEpoch", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CurrentEpoch.model_validate(data).network
