from _typeshed import Incomplete
from typing import Any

env: Incomplete
env_globals: dict[str, Any]
item_locals: dict[str, Any]

def add_filters(**mapping: dict[str, Any]): ...
def add_globals(**mapping: dict[str, Any]): ...
def add_locals(**mapping: dict[str, Any]): ...
def render(data: Any, context: dict | None = None): ...
