"""Data models for 나라장터 공공데이터개방표준 API."""

from typing import Optional, List, Any, Dict
from pydantic import BaseModel, Field
from datetime import datetime


class BidAnnouncement(BaseModel):
    """입찰공고정보 모델."""
    
    # 필수 항목
    bid_notice_no: str = Field(alias="bidNtceNo", description="입찰공고번호")
    pps_notice_yn: str = Field(alias="ppsNtceYn", description="나라장터공고여부")
    bid_notice_name: str = Field(alias="bidNtceNm", description="입찰공고명")
    bid_notice_status_name: str = Field(alias="bidNtceSttusNm", description="입찰공고상태명")
    bid_notice_date: str = Field(alias="bidNtceDate", description="입찰공고일자")
    bid_notice_begin: str = Field(alias="bidNtceBgn", description="입찰공고시각")
    business_div_name: str = Field(alias="bsnsDivNm", description="업무구분명")
    electronic_bid_yn: str = Field(alias="elctrnBidYn", description="전자입찰여부")
    contract_conclude_status_name: str = Field(alias="cntrctCnclsSttusNm", description="계약체결형태명")
    contract_conclude_method_name: str = Field(alias="cntrctCnclsMthdNm", description="계약체결방법명")
    notice_institution_name: str = Field(alias="ntceInsttNm", description="공고기관명")
    demand_institution_name: str = Field(alias="dmndInsttNm", description="수요기관명")
    opening_date: str = Field(alias="opengDate", description="개찰일자")
    opening_time: str = Field(alias="opengTm", description="개찰시각")
    opening_place: str = Field(alias="opengPlce", description="개찰장소")
    data_base_date: str = Field(alias="dataBssDate", description="데이터기준일자")
    
    # 선택 항목
    bid_notice_order: Optional[str] = Field(None, alias="bidNtceOrd", description="입찰공고차수")
    reference_notice_no: Optional[str] = Field(None, alias="refNtceNo", description="참조공고번호")
    reference_notice_order: Optional[str] = Field(None, alias="refNtceOrd", description="참조공고차수")
    international_bid_yn: Optional[str] = Field(None, alias="intrntnlBidYn", description="국제입찰여부")
    common_contract_yn: Optional[str] = Field(None, alias="cmmnCntrctYn", description="공동계약여부")
    common_receipt_method_name: Optional[str] = Field(None, alias="cmmnReciptMethdNm", description="공동수급방식명")
    bidwinner_decision_method_name: Optional[str] = Field(None, alias="bidwinrDcsnMthdNm", description="낙찰자결정방법명")
    notice_institution_code: Optional[str] = Field(None, alias="ntceInsttCd", description="공고기관코드")
    notice_institution_official_dept_name: Optional[str] = Field(None, alias="ntceInsttOfclDeptNm", description="공고기관담당자부서명")
    notice_institution_official_name: Optional[str] = Field(None, alias="ntceInsttOfclNm", description="공고기관담당자명")
    notice_institution_official_tel: Optional[str] = Field(None, alias="ntceInsttOfclTel", description="공고기관담당자전화번호")
    notice_institution_official_email: Optional[str] = Field(None, alias="ntceInsttOfclEmailAdrs", description="공고기관담당자이메일주소")
    demand_institution_code: Optional[str] = Field(None, alias="dmndInsttCd", description="수요기관코드")
    demand_institution_official_dept_name: Optional[str] = Field(None, alias="dmndInsttOfclDeptNm", description="수요기관담당자부서명")
    demand_institution_official_name: Optional[str] = Field(None, alias="dmndInsttOfclNm", description="수요기관담당자명")
    demand_institution_official_tel: Optional[str] = Field(None, alias="dmndInsttOfclTel", description="수요기관담당자전화번호")
    demand_institution_official_email: Optional[str] = Field(None, alias="dmndInsttOfclEmailAdrs", description="수요기관담당자이메일주소")
    presentation_operation_yn: Optional[str] = Field(None, alias="presnatnOprtnYn", description="설명회실시여부")
    presentation_operation_date: Optional[str] = Field(None, alias="presnatnOprtnDate", description="설명회실시일자")
    presentation_operation_time: Optional[str] = Field(None, alias="presnatnOprtnTm", description="설명회실시시각")
    presentation_operation_place: Optional[str] = Field(None, alias="presnatnOprtnPlce", description="설명회실시장소")
    bid_participation_qualification_register_close_date: Optional[str] = Field(None, alias="bidPrtcptQlfctRgstClseDate", description="입찰참가자격등록마감일자")
    bid_participation_qualification_register_close_time: Optional[str] = Field(None, alias="bidPrtcptQlfctRgstClseTm", description="입찰참가자격등록마감시각")
    common_receipt_agreement_close_date: Optional[str] = Field(None, alias="cmmnReciptAgrmntClseDate", description="공동수급협정마감일자")
    common_receipt_agreement_close_time: Optional[str] = Field(None, alias="cmmnReciptAgrmntClseTm", description="공동수급협정마감시각")
    bid_begin_date: Optional[str] = Field(None, alias="bidBeginDate", description="입찰개시일자")
    bid_begin_time: Optional[str] = Field(None, alias="bidBeginTm", description="입찰개시시각")
    bid_close_date: Optional[str] = Field(None, alias="bidClseDate", description="입찰마감일자")
    bid_close_time: Optional[str] = Field(None, alias="bidClseTm", description="입찰마감시각")
    assign_budget_amount: Optional[str] = Field(None, alias="asignBdgtAmt", description="배정예산금액(설계금액)")
    presumption_price: Optional[str] = Field(None, alias="presmptPrce", description="추정가격")
    reservation_price_decision_method_name: Optional[str] = Field(None, alias="rsrvtnPrceDcsnMthdNm", description="예정가격결정방법명")
    region_limit_yn: Optional[str] = Field(None, alias="rgnLmtYn", description="지역제한여부")
    participation_possible_region_name: Optional[str] = Field(None, alias="prtcptPsblRgnNm", description="참가가능지역명")
    industry_type_limit_yn: Optional[str] = Field(None, alias="indstrytyLmtYn", description="업종제한여부")
    bid_price_possible_industry_type_name: Optional[str] = Field(None, alias="bidprcPsblIndstrytyNm", description="투찰가능업종명")
    bid_notice_url: Optional[str] = Field(None, alias="bidNtceUrl", description="입찰공고URL")


class SuccessfulBid(BaseModel):
    """낙찰정보 모델."""
    
    # 필수 항목
    bid_notice_no: str = Field(alias="bidNtceNo", description="입찰공고번호")
    bid_notice_name: str = Field(alias="bidNtceNm", description="입찰공고명")
    business_div_name: str = Field(alias="bsnsDivNm", description="업무구분명")
    contract_conclude_status_name: str = Field(alias="cntrctCnclsSttusNm", description="계약체결형태명")
    contract_conclude_method_name: str = Field(alias="cntrctCnclsMthdNm", description="계약체결방법명")
    notice_institution_name: str = Field(alias="ntceInsttNm", description="공고기관명")
    demand_institution_name: str = Field(alias="dmndInsttNm", description="수요기관명")
    opening_date: str = Field(alias="opengDate", description="개찰일자")
    opening_time: str = Field(alias="opengTm", description="개찰시각")
    opening_result_div_name: str = Field(alias="opengRsltDivNm", description="개찰결과구분명")
    data_base_date: str = Field(alias="dataBssDate", description="데이터기준일자")
    
    # 선택 항목
    bid_notice_order: Optional[str] = Field(None, alias="bidNtceOrd", description="입찰공고차수")
    bidwinner_decision_method_name: Optional[str] = Field(None, alias="bidwinrDcsnMthdNm", description="낙찰자결정방법명")
    notice_institution_code: Optional[str] = Field(None, alias="ntceInsttCd", description="공고기관코드")
    demand_institution_code: Optional[str] = Field(None, alias="dmndInsttCd", description="수요기관코드")
    success_lowest_limit_rate: Optional[str] = Field(None, alias="sucsfLwstlmtRt", description="낙찰하한율")
    presumption_price: Optional[str] = Field(None, alias="presmptPrce", description="추정가격")
    reservation_price: Optional[str] = Field(None, alias="rsrvtnPrce", description="예정가격")
    base_amount: Optional[str] = Field(None, alias="bssAmt", description="기초금액")
    opening_rank: Optional[str] = Field(None, alias="opengRank", description="개찰순위")
    bid_price_corp_business_no: Optional[str] = Field(None, alias="bidprcCorpBizrno", description="투찰업체사업자등록번호")
    bid_price_corp_name: Optional[str] = Field(None, alias="bidprcCorpNm", description="투찰업체명")
    bid_price_corp_ceo_name: Optional[str] = Field(None, alias="bidprcCorpCeoNm", description="투찰업체대표자명")
    bid_price_amount: Optional[str] = Field(None, alias="bidprcAmt", description="투찰금액")
    bid_price_rate: Optional[str] = Field(None, alias="bidprcRt", description="투찰율")
    bid_price_date: Optional[str] = Field(None, alias="bidprcDate", description="투찰일자")
    bid_price_time: Optional[str] = Field(None, alias="bidprcTm", description="투찰시각")
    success_yn: Optional[str] = Field(None, alias="sucsfYn", description="낙찰여부")
    disqualification_reason: Optional[str] = Field(None, alias="dqlfctnRsn", description="부적격사유")
    final_success_amount: Optional[str] = Field(None, alias="fnlSucsfAmt", description="최종낙찰금액")
    final_success_rate: Optional[str] = Field(None, alias="fnlSucsfRt", description="최종낙찰율")
    final_success_date: Optional[str] = Field(None, alias="fnlSucsfDate", description="최종낙찰일자")
    final_success_corp_name: Optional[str] = Field(None, alias="fnlSucsfCorpNm", description="최종낙찰업체명")
    final_success_corp_ceo_name: Optional[str] = Field(None, alias="fnlSucsfCorpCeoNm", description="최종낙찰업체대표자명")
    final_success_corp_official_name: Optional[str] = Field(None, alias="fnlSucsfCorpOfclNm", description="최종낙찰업체담당자명")
    final_success_corp_business_no: Optional[str] = Field(None, alias="fnlSucsfCorpBizrno", description="최종낙찰업체사업자등록번호")
    final_success_corp_address: Optional[str] = Field(None, alias="fnlSucsfCorpAdrs", description="최종낙찰업체주소")
    final_success_corp_contact_tel: Optional[str] = Field(None, alias="fnlSucsfCorpContactTel", description="최종낙찰업체연락전화번호")


class Contract(BaseModel):
    """계약정보 모델."""
    
    # 필수 항목
    contract_no: str = Field(alias="cntrctNo", description="계약번호")
    contract_order: str = Field(alias="cntrctOrd", description="계약차수")
    contract_name: str = Field(alias="cntrctNm", description="계약명")
    business_div_name: str = Field(alias="bsnsDivNm", description="업무구분명")
    contract_conclude_status_name: str = Field(alias="cntrctCnclsSttusNm", description="계약체결형태명")
    contract_conclude_method_name: str = Field(alias="cntrctCnclsMthdNm", description="계약체결방법명")
    contract_conclude_date: str = Field(alias="cntrctCnclsDate", description="계약체결일자")
    contract_period: str = Field(alias="cntrctPrd", description="계약기간")
    contract_amount: str = Field(alias="cntrctAmt", description="계약금액")
    contract_institution_div_name: str = Field(alias="cntrctInsttDivNm", description="계약기관구분명")
    contract_institution_name: str = Field(alias="cntrctInsttNm", description="계약기관명")
    demand_institution_div_name: str = Field(alias="dmndInsttDivNm", description="수요기관구분명")
    demand_institution_name: str = Field(alias="dmndInsttNm", description="수요기관명")
    representative_corp_name: str = Field(alias="rprsntCorpNm", description="대표업체명")
    data_base_date: str = Field(alias="dataBssDate", description="데이터기준일자")
    
    # 선택 항목
    unity_contract_no: Optional[str] = Field(None, alias="untyCntrctNo", description="통합계약번호")
    longterm_continue_div_name: Optional[str] = Field(None, alias="lngtrmCtnuDivNm", description="장기계속구분명")
    common_contract_yn: Optional[str] = Field(None, alias="cmmnCntrctYn", description="공동계약여부")
    total_contract_amount: Optional[str] = Field(None, alias="ttalCntrctAmt", description="총계약금액")
    contract_info_url: Optional[str] = Field(None, alias="cntrctInfoUrl", description="계약정보URL")
    bid_notice_no: Optional[str] = Field(None, alias="bidNtceNo", description="입찰공고번호")
    bid_notice_order: Optional[str] = Field(None, alias="bidNtceOrd", description="입찰공고차수")
    bid_notice_name: Optional[str] = Field(None, alias="bidNtceNm", description="입찰공고명")
    opening_date: Optional[str] = Field(None, alias="opengDate", description="개찰일자")
    opening_time: Optional[str] = Field(None, alias="opengTm", description="개찰시각")
    reservation_price: Optional[str] = Field(None, alias="rsrvtnPrce", description="예정가격")
    private_contract_reason: Optional[str] = Field(None, alias="prvtcntrctRsn", description="수의계약사유")
    bid_notice_url: Optional[str] = Field(None, alias="bidNtceUrl", description="입찰공고URL")
    contract_institution_code: Optional[str] = Field(None, alias="cntrctInsttCd", description="계약기관코드")
    contract_institution_charge_dept_name: Optional[str] = Field(None, alias="cntrctInsttChrgDeptNm", description="계약기관담당부서명")
    contract_institution_official_name: Optional[str] = Field(None, alias="cntrctInsttOfclNm", description="계약기관담당자명")
    contract_institution_official_tel: Optional[str] = Field(None, alias="cntrctInsttOfclTel", description="계약기관담당자전화번호")
    contract_institution_official_email: Optional[str] = Field(None, alias="cntrctInsttOfcl", description="계약기관담당자이메일주소")
    demand_institution_code: Optional[str] = Field(None, alias="dmndInsttCd", description="수요기관코드")
    demand_institution_official_dept_name: Optional[str] = Field(None, alias="dmndInsttOfclDeptNm", description="수요기관담당자부서명")
    demand_institution_official_name: Optional[str] = Field(None, alias="dmndInsttOfclNm", description="수요기관담당자명")
    demand_institution_official_tel: Optional[str] = Field(None, alias="dmndInsttOfclTel", description="수요기관담당자전화번호")
    demand_institution_official_email: Optional[str] = Field(None, alias="dmndInsttOfclEmailAdrs", description="수요기관담당자이메일주소")
    domestic_corp_yn: Optional[str] = Field(None, alias="dmstcCorpYn", description="국내업체여부")
    representative_corp_ceo_name: Optional[str] = Field(None, alias="rprsntCorpCeoNm", description="대표업체대표자명")
    representative_corp_official_name: Optional[str] = Field(None, alias="rprsntCorpOfclNm", description="대표업체담당자명")
    representative_corp_business_no: Optional[str] = Field(None, alias="rprsntCorpBizrno", description="대표업체사업자등록번호")
    representative_corp_address: Optional[str] = Field(None, alias="rprsntCorpAdrs", description="대표업체주소")
    representative_corp_contact_tel: Optional[str] = Field(None, alias="rprsntCorpContactTel", description="대표업체연락전화번호")