# generated by datamodel-codegen:
#   filename:  placement.json
#   timestamp: 2025-09-18T11:39:58+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Position: List[float] = Field(..., description='Position')
    Axis: List[float] = Field(..., description='Rotation Axis')
    Angle: float = Field(..., description='Rotation Angle (degrees)')
