
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-15T16:43:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4fdfdf982942f97fb42524b637ee5af60e140b7",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
