from .utils import calculate_settings as calculate_settings, torch_gpu_device as torch_gpu_device, triton_tanh as triton_tanh

def geglu_exact_forward_kernel(gate, up): ...
def geglu_exact_backward_kernel(DW, e, g): ...
def geglu_approx_forward_kernel(gate, up): ...
def geglu_approx_backward_kernel(DW, e, g): ...
