
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-16T16:57:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "74cc78456f772030b116b098470a1c1a872512f2",
 "version": "3.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
