"""Utility functions and helpers for the comparison framework.

Copyright (c) 2025 Jim Schilling.
Licensed under the MIT License. See the LICENSE file for details.
"""

from .config_helpers import (
    apply_environment_overrides,
    create_comparison_config_from_lazyframes,
    create_config_from_dataframes,
    create_default_config,
    get_config_value,
    get_env_config,
    load_config_from_file,
    merge_configs,
    save_config_to_file,
    set_nested_config_value,
    validate_config,
)
from .constants import (
    ALL_COLUMNS_PRESENT_MSG,
    ALL_DTYPES_CORRECT_MSG,
    ALL_PATTERNS_CORRECT_MSG,
    ALL_RANGES_CORRECT_MSG,
    ALL_UNIQUE_MSG,
    COMPARISON_RESULTS_SECTION,
    # Validation constants
    COMPLETENESS_FAILED_MSG,
    DEFAULT_FORMAT,
    DEFAULT_MAX_SAMPLES,
    # File and output constants
    DEFAULT_OUTPUT_DIR,
    DTYPE_FAILED_MSG,
    DUPLICATE_PK_MSG,
    # Thresholds and limits
    DUPLICATE_THRESHOLD,
    EMPTY_LEFT_SCHEMA_MSG,
    EMPTY_RIGHT_SCHEMA_MSG,
    FIRST_COLUMN_INDEX,
    FORMAT_CSV,
    FORMAT_JSON,
    FORMAT_PARQUET,
    # Join and comparison constants
    JOIN_INNER,
    JOIN_LEFT,
    JSON_INDENT,
    LEFT_DF_NAME,
    LEFT_ONLY_FILENAME,
    LEFT_ONLY_SECTION,
    LEFT_PREFIX,
    LEN_COLUMN,
    # Error message patterns
    MISSING_COLUMNS_MSG,
    MISSING_LEFT_MAPPED_MSG,
    MISSING_RIGHT_MAPPED_MSG,
    NO_PK_MSG,
    NULL_VIOLATION_MSG,
    PATTERN_FAILED_MSG,
    PERCENTAGE_FORMAT,
    PERCENTAGE_MULTIPLIER,
    PERCENTAGES_SECTION,
    PK_NOT_DEFINED_MSG,
    PK_NOT_MAPPED_MSG,
    # Column prefixes and naming
    PRIMARY_KEY_PREFIX,
    RANGE_FAILED_MSG,
    # Report section headers
    RECORD_COUNTS_SECTION,
    REPORT_HEADER,
    # Report formatting constants
    REPORT_HEADER_LENGTH,
    REPORT_TITLE,
    RIGHT_DF_NAME,
    RIGHT_ONLY_FILENAME,
    RIGHT_ONLY_SECTION,
    RIGHT_PREFIX,
    SECTION_SEPARATOR,
    SECTION_SEPARATOR_LENGTH,
    SUMMARY_FILENAME,
    TIMESTAMP_FORMAT,
    UNIQUENESS_FAILED_MSG,
    VALIDATION_SUCCESS_MSG,
    # Filename patterns
    VALUE_DIFFERENCES_FILENAME,
    VALUE_DIFFERENCES_SECTION,
    WRONG_DTYPE_MSG,
    ZERO_THRESHOLD,
)
from .data_helpers import (
    compare_dataframe_shapes,
    estimate_dataframe_memory,
    get_dataframe_info,
    get_null_summary,
    has_null_values,
    optimize_dataframe,
    safe_collect,
    validate_dataframe,
)
from .file_operations import (
    ensure_directory_exists,
    export_lazyframe,
    get_export_file_paths,
    get_file_extension,
    import_lazyframe,
    list_files_by_pattern,
    validate_file_path,
)
from .formatting import (
    create_summary_table,
    format_column_list,
    format_dataframe_sample,
    format_large_number,
    format_number,
    format_percentage,
    format_validation_errors,
    truncate_string,
)
from .logging_helpers import (
    create_log_message,
    create_operation_context,
    create_service_health_check,
    log_dataframe_stats,
    log_performance,
    log_service_health,
    log_service_initialization,
    log_service_operation,
    performance_monitor,
    update_operation_context,
)
from .type_helpers import get_polars_datatype_name, is_numeric_datatype

__all__ = [
    # Constants
    "PRIMARY_KEY_PREFIX",
    "LEFT_PREFIX",
    "RIGHT_PREFIX",
    "LEFT_DF_NAME",
    "RIGHT_DF_NAME",
    "JOIN_INNER",
    "JOIN_LEFT",
    "LEN_COLUMN",
    "DUPLICATE_THRESHOLD",
    "ZERO_THRESHOLD",
    "DEFAULT_MAX_SAMPLES",
    "PERCENTAGE_MULTIPLIER",
    "PERCENTAGE_FORMAT",
    "JSON_INDENT",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_FORMAT",
    "FORMAT_PARQUET",
    "FORMAT_CSV",
    "FORMAT_JSON",
    "VALUE_DIFFERENCES_FILENAME",
    "LEFT_ONLY_FILENAME",
    "RIGHT_ONLY_FILENAME",
    "SUMMARY_FILENAME",
    "TIMESTAMP_FORMAT",
    "REPORT_HEADER_LENGTH",
    "SECTION_SEPARATOR_LENGTH",
    "REPORT_HEADER",
    "REPORT_TITLE",
    "SECTION_SEPARATOR",
    "RECORD_COUNTS_SECTION",
    "COMPARISON_RESULTS_SECTION",
    "PERCENTAGES_SECTION",
    "VALUE_DIFFERENCES_SECTION",
    "LEFT_ONLY_SECTION",
    "RIGHT_ONLY_SECTION",
    "MISSING_COLUMNS_MSG",
    "WRONG_DTYPE_MSG",
    "NULL_VIOLATION_MSG",
    "PK_NOT_DEFINED_MSG",
    "EMPTY_LEFT_SCHEMA_MSG",
    "EMPTY_RIGHT_SCHEMA_MSG",
    "NO_PK_MSG",
    "MISSING_LEFT_MAPPED_MSG",
    "MISSING_RIGHT_MAPPED_MSG",
    "PK_NOT_MAPPED_MSG",
    "DUPLICATE_PK_MSG",
    "COMPLETENESS_FAILED_MSG",
    "ALL_COLUMNS_PRESENT_MSG",
    "DTYPE_FAILED_MSG",
    "ALL_DTYPES_CORRECT_MSG",
    "RANGE_FAILED_MSG",
    "ALL_RANGES_CORRECT_MSG",
    "PATTERN_FAILED_MSG",
    "ALL_PATTERNS_CORRECT_MSG",
    "UNIQUENESS_FAILED_MSG",
    "ALL_UNIQUE_MSG",
    "VALIDATION_SUCCESS_MSG",
    "FIRST_COLUMN_INDEX",
    # File operations
    "ensure_directory_exists",
    "export_lazyframe",
    "get_export_file_paths",
    "get_file_extension",
    "import_lazyframe",
    "list_files_by_pattern",
    "validate_file_path",
    # Formatting functions
    "create_summary_table",
    "format_column_list",
    "format_dataframe_sample",
    "format_large_number",
    "format_number",
    "format_percentage",
    "format_validation_errors",
    "truncate_string",
    # Configuration helpers
    "apply_environment_overrides",
    "create_comparison_config_from_lazyframes",
    "create_config_from_dataframes",
    "create_default_config",
    "get_config_value",
    "get_env_config",
    "load_config_from_file",
    "merge_configs",
    "save_config_to_file",
    "set_nested_config_value",
    "validate_config",
    # Data helpers
    "compare_dataframe_shapes",
    "estimate_dataframe_memory",
    "get_dataframe_info",
    "get_null_summary",
    "has_null_values",
    "optimize_dataframe",
    "safe_collect",
    "validate_dataframe",
    # Logging helpers
    "create_log_message",
    "create_operation_context",
    "create_service_health_check",
    "log_dataframe_stats",
    "log_performance",
    "log_service_health",
    "log_service_initialization",
    "log_service_operation",
    "performance_monitor",
    "update_operation_context",
    # Type helpers
    "is_numeric_datatype",
    "get_polars_datatype_name",
]

DOMAINS: list[str] = ["utils", "helpers", "io"]
