# Generated by ariadne-codegen
# Source: codegen/network_subgraph/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class SubgraphDeploymentManifest(BaseModel):
    subgraph_deployment_manifest: Optional[
        "SubgraphDeploymentManifestSubgraphDeploymentManifest"
    ] = Field(alias="subgraphDeploymentManifest")


class SubgraphDeploymentManifestSubgraphDeploymentManifest(BaseModel):
    start_block: Optional[int] = Field(alias="startBlock")
    network: Optional[str]


SubgraphDeploymentManifest.model_rebuild()
