# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: truffle/os/task_queries.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'truffle/os/task_queries.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtruffle/os/task_queries.proto\x12\ntruffle.os\x1a google/protobuf/field_mask.proto\"{\n\x0fGetTasksRequest\x12\x10\n\x08task_ids\x18\x01 \x03(\t\x12\x33\n\nfield_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMaskH\x00\x88\x01\x01\x12\x12\n\nwith_nodes\x18\x03 \x01(\x08\x42\r\n\x0b_field_mask\"|\n\x11GetOneTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x33\n\nfield_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMaskH\x00\x88\x01\x01\x12\x12\n\nwith_nodes\x18\x03 \x01(\x08\x42\r\n\x0b_field_mask\"\xa9\x01\n\x13GetTaskNodesRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08node_ids\x18\x02 \x03(\x04\x12\x11\n\trecursive\x18\x03 \x01(\x08\x12-\n\tnode_mask\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\x12-\n\titem_mask\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.FieldMaskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truffle.os.task_queries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTASKSREQUEST']._serialized_start=79
  _globals['_GETTASKSREQUEST']._serialized_end=202
  _globals['_GETONETASKREQUEST']._serialized_start=204
  _globals['_GETONETASKREQUEST']._serialized_end=328
  _globals['_GETTASKNODESREQUEST']._serialized_start=331
  _globals['_GETTASKNODESREQUEST']._serialized_end=500
# @@protoc_insertion_point(module_scope)
