from _typeshed import Incomplete
from collections.abc import Generator
from hexcore.infrastructure.repositories.orms.sqlalchemy.session import AsyncSessionLocal as AsyncSessionLocal
from hexcore.infrastructure.uow import NoSqlUnitOfWork as NoSqlUnitOfWork, SqlAlchemyUnitOfWork as SqlAlchemyUnitOfWork
from sqlalchemy.ext.asyncio import AsyncSession as AsyncSession

async def get_session() -> Generator[Incomplete]: ...
async def get_sql_uow(session: AsyncSession = ...): ...
async def get_nosql_uow() -> Generator[Incomplete]: ...
