""" This file is automatically generated from "mitsuba.conf" using the script
    "resources/configure.py". Please do not attempt to change it manually,
    as any changes will be overwritten."""

PYTHON_EXECUTABLE = r"/private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/cibw-run-4gogdcxf/cp39-macosx_arm64/build/venv/bin/python"
MI_DEFAULT_VARIANT = ''
MI_VARIANTS = ['scalar_rgb', 'scalar_spectral', 'scalar_spectral_polarized', 'llvm_ad_rgb', 'llvm_ad_mono', 'llvm_ad_mono_polarized', 'llvm_ad_spectral', 'llvm_ad_spectral_polarized']
DRJIT_VERSION_REQUIREMENT = '1.2.0'
CXX_COMPILER = 'AppleClang 15.0.0.15000309'
