import logging
from _typeshed import Incomplete

UNSLOTH_ENABLE_LOGGING: Incomplete

class HideLoggingMessage(logging.Filter):
    text: Incomplete
    def __init__(self, text) -> None: ...
    def filter(self, x): ...

def fix_message_factory_issue(): ...
def fix_xformers_performance_issue() -> None: ...
def fix_vllm_aimv2_issue() -> None: ...
def ignore_logger_messages() -> None: ...
