# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rbt/v1alpha1/config_mode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rbt.v1alpha1 import application_config_pb2 as rbt_dot_v1alpha1_dot_application__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1erbt/v1alpha1/config_mode.proto\x12\x0crbt.v1alpha1\x1a%rbt/v1alpha1/application_config.proto\"\x12\n\x10GetConfigRequest\"P\n\x11GetConfigResponse\x12;\n\x12\x61pplication_config\x18\x01 \x01(\x0b\x32\x1f.rbt.v1alpha1.ApplicationConfig2P\n\x06\x43onfig\x12\x46\n\x03Get\x12\x1e.rbt.v1alpha1.GetConfigRequest\x1a\x1f.rbt.v1alpha1.GetConfigResponseb\x06proto3')



_GETCONFIGREQUEST = DESCRIPTOR.message_types_by_name['GetConfigRequest']
_GETCONFIGRESPONSE = DESCRIPTOR.message_types_by_name['GetConfigResponse']
GetConfigRequest = _reflection.GeneratedProtocolMessageType('GetConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGREQUEST,
  '__module__' : 'rbt.v1alpha1.config_mode_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.GetConfigRequest)
  })
_sym_db.RegisterMessage(GetConfigRequest)

GetConfigResponse = _reflection.GeneratedProtocolMessageType('GetConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGRESPONSE,
  '__module__' : 'rbt.v1alpha1.config_mode_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.GetConfigResponse)
  })
_sym_db.RegisterMessage(GetConfigResponse)

_CONFIG = DESCRIPTOR.services_by_name['Config']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETCONFIGREQUEST._serialized_start=87
  _GETCONFIGREQUEST._serialized_end=105
  _GETCONFIGRESPONSE._serialized_start=107
  _GETCONFIGRESPONSE._serialized_end=187
  _CONFIG._serialized_start=189
  _CONFIG._serialized_end=269
# @@protoc_insertion_point(module_scope)
