import typing as t
from hexcore.domain.events import DomainEvent as DomainEvent, IEventDispatcher as IEventDispatcher

class InMemoryEventDispatcher(IEventDispatcher):
    def __init__(self) -> None: ...
    async def dispatch(self, event: DomainEvent) -> None: ...
    def register(self, event_type: type[DomainEvent], handler: t.Callable[[DomainEvent], t.Awaitable[None]]) -> None: ...
    def clear_events(self) -> None: ...
