# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _wc_ode
else:
    import _wc_ode

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wc_ode.delete_SwigPyIterator

    def value(self):
        return _wc_ode.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _wc_ode.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _wc_ode.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _wc_ode.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _wc_ode.SwigPyIterator_equal(self, x)

    def copy(self):
        return _wc_ode.SwigPyIterator_copy(self)

    def next(self):
        return _wc_ode.SwigPyIterator_next(self)

    def __next__(self):
        return _wc_ode.SwigPyIterator___next__(self)

    def previous(self):
        return _wc_ode.SwigPyIterator_previous(self)

    def advance(self, n):
        return _wc_ode.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _wc_ode.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _wc_ode.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _wc_ode.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _wc_ode.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _wc_ode.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _wc_ode.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _wc_ode:
_wc_ode.SwigPyIterator_swigregister(SwigPyIterator)
class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _wc_ode.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _wc_ode.IntVector___nonzero__(self)

    def __bool__(self):
        return _wc_ode.IntVector___bool__(self)

    def __len__(self):
        return _wc_ode.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _wc_ode.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _wc_ode.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _wc_ode.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _wc_ode.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _wc_ode.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _wc_ode.IntVector___setitem__(self, *args)

    def pop(self):
        return _wc_ode.IntVector_pop(self)

    def append(self, x):
        return _wc_ode.IntVector_append(self, x)

    def empty(self):
        return _wc_ode.IntVector_empty(self)

    def size(self):
        return _wc_ode.IntVector_size(self)

    def swap(self, v):
        return _wc_ode.IntVector_swap(self, v)

    def begin(self):
        return _wc_ode.IntVector_begin(self)

    def end(self):
        return _wc_ode.IntVector_end(self)

    def rbegin(self):
        return _wc_ode.IntVector_rbegin(self)

    def rend(self):
        return _wc_ode.IntVector_rend(self)

    def clear(self):
        return _wc_ode.IntVector_clear(self)

    def get_allocator(self):
        return _wc_ode.IntVector_get_allocator(self)

    def pop_back(self):
        return _wc_ode.IntVector_pop_back(self)

    def erase(self, *args):
        return _wc_ode.IntVector_erase(self, *args)

    def __init__(self, *args):
        _wc_ode.IntVector_swiginit(self, _wc_ode.new_IntVector(*args))

    def push_back(self, x):
        return _wc_ode.IntVector_push_back(self, x)

    def front(self):
        return _wc_ode.IntVector_front(self)

    def back(self):
        return _wc_ode.IntVector_back(self)

    def assign(self, n, x):
        return _wc_ode.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _wc_ode.IntVector_resize(self, *args)

    def insert(self, *args):
        return _wc_ode.IntVector_insert(self, *args)

    def reserve(self, n):
        return _wc_ode.IntVector_reserve(self, n)

    def capacity(self):
        return _wc_ode.IntVector_capacity(self)
    __swig_destroy__ = _wc_ode.delete_IntVector

# Register IntVector in _wc_ode:
_wc_ode.IntVector_swigregister(IntVector)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _wc_ode.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _wc_ode.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _wc_ode.DoubleVector___bool__(self)

    def __len__(self):
        return _wc_ode.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _wc_ode.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _wc_ode.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _wc_ode.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _wc_ode.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _wc_ode.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _wc_ode.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _wc_ode.DoubleVector_pop(self)

    def append(self, x):
        return _wc_ode.DoubleVector_append(self, x)

    def empty(self):
        return _wc_ode.DoubleVector_empty(self)

    def size(self):
        return _wc_ode.DoubleVector_size(self)

    def swap(self, v):
        return _wc_ode.DoubleVector_swap(self, v)

    def begin(self):
        return _wc_ode.DoubleVector_begin(self)

    def end(self):
        return _wc_ode.DoubleVector_end(self)

    def rbegin(self):
        return _wc_ode.DoubleVector_rbegin(self)

    def rend(self):
        return _wc_ode.DoubleVector_rend(self)

    def clear(self):
        return _wc_ode.DoubleVector_clear(self)

    def get_allocator(self):
        return _wc_ode.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _wc_ode.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _wc_ode.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _wc_ode.DoubleVector_swiginit(self, _wc_ode.new_DoubleVector(*args))

    def push_back(self, x):
        return _wc_ode.DoubleVector_push_back(self, x)

    def front(self):
        return _wc_ode.DoubleVector_front(self)

    def back(self):
        return _wc_ode.DoubleVector_back(self)

    def assign(self, n, x):
        return _wc_ode.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _wc_ode.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _wc_ode.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _wc_ode.DoubleVector_reserve(self, n)

    def capacity(self):
        return _wc_ode.DoubleVector_capacity(self)
    __swig_destroy__ = _wc_ode.delete_DoubleVector

# Register DoubleVector in _wc_ode:
_wc_ode.DoubleVector_swigregister(DoubleVector)
class DoubleVector2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _wc_ode.DoubleVector2_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _wc_ode.DoubleVector2___nonzero__(self)

    def __bool__(self):
        return _wc_ode.DoubleVector2___bool__(self)

    def __len__(self):
        return _wc_ode.DoubleVector2___len__(self)

    def __getslice__(self, i, j):
        return _wc_ode.DoubleVector2___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _wc_ode.DoubleVector2___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _wc_ode.DoubleVector2___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _wc_ode.DoubleVector2___delitem__(self, *args)

    def __getitem__(self, *args):
        return _wc_ode.DoubleVector2___getitem__(self, *args)

    def __setitem__(self, *args):
        return _wc_ode.DoubleVector2___setitem__(self, *args)

    def pop(self):
        return _wc_ode.DoubleVector2_pop(self)

    def append(self, x):
        return _wc_ode.DoubleVector2_append(self, x)

    def empty(self):
        return _wc_ode.DoubleVector2_empty(self)

    def size(self):
        return _wc_ode.DoubleVector2_size(self)

    def swap(self, v):
        return _wc_ode.DoubleVector2_swap(self, v)

    def begin(self):
        return _wc_ode.DoubleVector2_begin(self)

    def end(self):
        return _wc_ode.DoubleVector2_end(self)

    def rbegin(self):
        return _wc_ode.DoubleVector2_rbegin(self)

    def rend(self):
        return _wc_ode.DoubleVector2_rend(self)

    def clear(self):
        return _wc_ode.DoubleVector2_clear(self)

    def get_allocator(self):
        return _wc_ode.DoubleVector2_get_allocator(self)

    def pop_back(self):
        return _wc_ode.DoubleVector2_pop_back(self)

    def erase(self, *args):
        return _wc_ode.DoubleVector2_erase(self, *args)

    def __init__(self, *args):
        _wc_ode.DoubleVector2_swiginit(self, _wc_ode.new_DoubleVector2(*args))

    def push_back(self, x):
        return _wc_ode.DoubleVector2_push_back(self, x)

    def front(self):
        return _wc_ode.DoubleVector2_front(self)

    def back(self):
        return _wc_ode.DoubleVector2_back(self)

    def assign(self, n, x):
        return _wc_ode.DoubleVector2_assign(self, n, x)

    def resize(self, *args):
        return _wc_ode.DoubleVector2_resize(self, *args)

    def insert(self, *args):
        return _wc_ode.DoubleVector2_insert(self, *args)

    def reserve(self, n):
        return _wc_ode.DoubleVector2_reserve(self, n)

    def capacity(self):
        return _wc_ode.DoubleVector2_capacity(self)
    __swig_destroy__ = _wc_ode.delete_DoubleVector2

# Register DoubleVector2 in _wc_ode:
_wc_ode.DoubleVector2_swigregister(DoubleVector2)
class SingleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _wc_ode.SingleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _wc_ode.SingleVector___nonzero__(self)

    def __bool__(self):
        return _wc_ode.SingleVector___bool__(self)

    def __len__(self):
        return _wc_ode.SingleVector___len__(self)

    def __getslice__(self, i, j):
        return _wc_ode.SingleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _wc_ode.SingleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _wc_ode.SingleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _wc_ode.SingleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _wc_ode.SingleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _wc_ode.SingleVector___setitem__(self, *args)

    def pop(self):
        return _wc_ode.SingleVector_pop(self)

    def append(self, x):
        return _wc_ode.SingleVector_append(self, x)

    def empty(self):
        return _wc_ode.SingleVector_empty(self)

    def size(self):
        return _wc_ode.SingleVector_size(self)

    def swap(self, v):
        return _wc_ode.SingleVector_swap(self, v)

    def begin(self):
        return _wc_ode.SingleVector_begin(self)

    def end(self):
        return _wc_ode.SingleVector_end(self)

    def rbegin(self):
        return _wc_ode.SingleVector_rbegin(self)

    def rend(self):
        return _wc_ode.SingleVector_rend(self)

    def clear(self):
        return _wc_ode.SingleVector_clear(self)

    def get_allocator(self):
        return _wc_ode.SingleVector_get_allocator(self)

    def pop_back(self):
        return _wc_ode.SingleVector_pop_back(self)

    def erase(self, *args):
        return _wc_ode.SingleVector_erase(self, *args)

    def __init__(self, *args):
        _wc_ode.SingleVector_swiginit(self, _wc_ode.new_SingleVector(*args))

    def push_back(self, x):
        return _wc_ode.SingleVector_push_back(self, x)

    def front(self):
        return _wc_ode.SingleVector_front(self)

    def back(self):
        return _wc_ode.SingleVector_back(self)

    def assign(self, n, x):
        return _wc_ode.SingleVector_assign(self, n, x)

    def resize(self, *args):
        return _wc_ode.SingleVector_resize(self, *args)

    def insert(self, *args):
        return _wc_ode.SingleVector_insert(self, *args)

    def reserve(self, n):
        return _wc_ode.SingleVector_reserve(self, n)

    def capacity(self):
        return _wc_ode.SingleVector_capacity(self)
    __swig_destroy__ = _wc_ode.delete_SingleVector

# Register SingleVector in _wc_ode:
_wc_ode.SingleVector_swigregister(SingleVector)
class SingleVector2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _wc_ode.SingleVector2_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _wc_ode.SingleVector2___nonzero__(self)

    def __bool__(self):
        return _wc_ode.SingleVector2___bool__(self)

    def __len__(self):
        return _wc_ode.SingleVector2___len__(self)

    def __getslice__(self, i, j):
        return _wc_ode.SingleVector2___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _wc_ode.SingleVector2___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _wc_ode.SingleVector2___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _wc_ode.SingleVector2___delitem__(self, *args)

    def __getitem__(self, *args):
        return _wc_ode.SingleVector2___getitem__(self, *args)

    def __setitem__(self, *args):
        return _wc_ode.SingleVector2___setitem__(self, *args)

    def pop(self):
        return _wc_ode.SingleVector2_pop(self)

    def append(self, x):
        return _wc_ode.SingleVector2_append(self, x)

    def empty(self):
        return _wc_ode.SingleVector2_empty(self)

    def size(self):
        return _wc_ode.SingleVector2_size(self)

    def swap(self, v):
        return _wc_ode.SingleVector2_swap(self, v)

    def begin(self):
        return _wc_ode.SingleVector2_begin(self)

    def end(self):
        return _wc_ode.SingleVector2_end(self)

    def rbegin(self):
        return _wc_ode.SingleVector2_rbegin(self)

    def rend(self):
        return _wc_ode.SingleVector2_rend(self)

    def clear(self):
        return _wc_ode.SingleVector2_clear(self)

    def get_allocator(self):
        return _wc_ode.SingleVector2_get_allocator(self)

    def pop_back(self):
        return _wc_ode.SingleVector2_pop_back(self)

    def erase(self, *args):
        return _wc_ode.SingleVector2_erase(self, *args)

    def __init__(self, *args):
        _wc_ode.SingleVector2_swiginit(self, _wc_ode.new_SingleVector2(*args))

    def push_back(self, x):
        return _wc_ode.SingleVector2_push_back(self, x)

    def front(self):
        return _wc_ode.SingleVector2_front(self)

    def back(self):
        return _wc_ode.SingleVector2_back(self)

    def assign(self, n, x):
        return _wc_ode.SingleVector2_assign(self, n, x)

    def resize(self, *args):
        return _wc_ode.SingleVector2_resize(self, *args)

    def insert(self, *args):
        return _wc_ode.SingleVector2_insert(self, *args)

    def reserve(self, n):
        return _wc_ode.SingleVector2_reserve(self, n)

    def capacity(self):
        return _wc_ode.SingleVector2_capacity(self)
    __swig_destroy__ = _wc_ode.delete_SingleVector2

# Register SingleVector2 in _wc_ode:
_wc_ode.SingleVector2_swigregister(SingleVector2)
class WC_ode(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, N, dt, P, Q, x0, weights, t_end=300.0, t_cut=0.0, c_ee=16.0, c_ei=12.0, c_ie=15.0, c_ii=3.0, tau_e=8.0, tau_i=8.0, a_e=1.3, a_i=2.0, b_e=4.0, b_i=3.7, c_e=1.0, c_i=1.0, theta_i=0.0, theta_e=0.0, r_e=1.0, r_i=1.0, k_e=0.994, k_i=0.999, alpha_e=1.0, alpha_i=1.0, g_e=0.0, g_i=0.0, fix_seed=0):
        _wc_ode.WC_ode_swiginit(self, _wc_ode.new_WC_ode(N, dt, P, Q, x0, weights, t_end, t_cut, c_ee, c_ei, c_ie, c_ii, tau_e, tau_i, a_e, a_i, b_e, b_i, c_e, c_i, theta_i, theta_e, r_e, r_i, k_e, k_i, alpha_e, alpha_i, g_e, g_i, fix_seed))

    def sigmoid(self, x, a, b, c):
        return _wc_ode.WC_ode_sigmoid(self, x, a, b, c)

    def rhs(self, y, dydt, dt):
        return _wc_ode.WC_ode_rhs(self, y, dydt, dt)

    def euler_step(self, y, dt):
        return _wc_ode.WC_ode_euler_step(self, y, dt)

    def eulerIntegrate(self):
        return _wc_ode.WC_ode_eulerIntegrate(self)

    def heun_step(self, y, dt):
        return _wc_ode.WC_ode_heun_step(self, y, dt)

    def heunIntegrate(self):
        return _wc_ode.WC_ode_heunIntegrate(self)

    def rk4_step(self, y, dt):
        return _wc_ode.WC_ode_rk4_step(self, y, dt)

    def rk4Integrate(self):
        return _wc_ode.WC_ode_rk4Integrate(self)

    def get_states(self):
        return _wc_ode.WC_ode_get_states(self)

    def get_times(self):
        return _wc_ode.WC_ode_get_times(self)
    __swig_destroy__ = _wc_ode.delete_WC_ode

# Register WC_ode in _wc_ode:
_wc_ode.WC_ode_swigregister(WC_ode)

