from .edits import del_, ins
from .embedded import (
    area,  # canonical area
    audio,
    audio_source,
    canvas,  # canonical canvas
    embed,
    iframe,
    img,
    map as _map,  # avoid shadowing built-in
    object as _object,  # avoid shadowing built-in
    param,
    picture,
    source,
    svg,
    track,
    video,
    video_source,
)
from .forms import (
    button,
    datalist,
    fieldset,
    form,
    input as _input,  # avoid shadowing built-in
    label,
    legend,
    meter,
    optgroup,
    option,
    output,
    progress,
    select,
    textarea,
)
from .grouping import (
    blockquote,
    dd,
    div,
    dl,
    dt,
    figcaption,
    figure,
    hr,
    li,
    main,  # canonical main
    menu,
    ol,
    p,
    pre,
    search,
    ul,
)
from .head import (
    base,
    head,
    link,
    meta,
    style,
    title,
)
from .links import (
    a,  # canonical <a>
    area as area_link,  # avoid clobbering embedded.area
)
from .scripting import (
    canvas as canvas_script,  # avoid clobbering embedded.canvas
    noscript,
    script,
    slot,
    template,
)
from .sections import (
    address,
    article,
    aside,
    body,
    footer,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    header,
    hgroup,
    main as main_section,  # avoid clobbering grouping.main
    nav,
    section,
)
from .table import (
    caption,
    col,
    colgroup,
    table,
    tbody,
    td,
    tfoot,
    th,
    thead,
    tr,
)
from .text import (
    a as a_text,  # avoid clobbering links.a
    abbr,
    b,
    bdi,
    bdo,
    br,
    cite,
    code,
    data,
    dfn,
    em,
    i,
    kbd,
    mark,
    q,
    rb,
    rp,
    rt,
    ruby,
    s,
    samp,
    small,
    span,
    strong,
    sub,
    sup,
    time,
    u,
    var,
    wbr,
)

object = _object
map = _map
input = _input

__all__ = [
    # edits.py
    "ins",
    "del_",
    # embedded.py
    "img",
    "picture",
    "source",
    "track",
    "audio",
    "video",
    "audio_source",
    "video_source",
    "embed",
    "iframe",
    "object",
    "param",
    "canvas",
    "svg",
    "map",
    "area",
    # forms.py
    "form",
    "input",
    "textarea",
    "select",
    "option",
    "optgroup",
    "label",
    "button",
    "fieldset",
    "legend",
    "datalist",
    "output",
    "meter",
    "progress",
    # grouping.py
    "p",
    "hr",
    "pre",
    "blockquote",
    "ol",
    "ul",
    "li",
    "dl",
    "dt",
    "dd",
    "figure",
    "figcaption",
    "div",
    "main",
    "menu",
    "search",
    # links.py
    "a",
    "link",
    "area_link",
    # metadata.py
    "title",
    "base",
    "link",
    "meta",
    "style",
    "head",
    # scripting.py
    "script",
    "noscript",
    "template",
    "slot",
    "canvas_script",
    # sections.py
    "section",
    "article",
    "nav",
    "aside",
    "header",
    "footer",
    "main_section",
    "address",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hgroup",
    "body",
    # table.py
    "table",
    "caption",
    "colgroup",
    "col",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    # text.py
    "a_text",
    "abbr",
    "b",
    "bdi",
    "bdo",
    "br",
    "cite",
    "code",
    "data",
    "dfn",
    "em",
    "i",
    "kbd",
    "mark",
    "q",
    "rb",
    "rp",
    "rt",
    "ruby",
    "s",
    "samp",
    "small",
    "span",
    "strong",
    "sub",
    "sup",
    "time",
    "u",
    "var",
    "wbr",
]
