"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sponsorschema import SponsorSchema, SponsorSchemaTypedDict
from owasp_nest.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PagedSponsorSchemaTypedDict(TypedDict):
    items: List[SponsorSchemaTypedDict]
    count: int


class PagedSponsorSchema(BaseModel):
    items: List[SponsorSchema]

    count: int
