import pytest
from _pytest.fixtures import FixtureManager as FixtureManager, FuncFixtureInfo
from typing import Any, Callable

def getfuncargnames(node: pytest.Item) -> tuple[str, ...]: ...
def getfixtureinfo(self, node: pytest.Item, func: Callable[..., object] | None, cls: Any | None) -> FuncFixtureInfo: ...
def get_argnames_with_parametrize_marker(*args, **kwargs): ...
