# Generated by Django 3.2.12 on 2023-12-08 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novadata_utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novadatamodel',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novadatamodel_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de criação'),
        ),
    ]
