from ece241_submission_static_analyzer.rules.function_must_return import FunctionMustReturnRule
from ece241_submission_static_analyzer.rules.require_class import RequireClassRule
from ece241_submission_static_analyzer.rules.require_file import RequireFileRule
from ece241_submission_static_analyzer.rules.require_function import RequireFunctionRule
from ece241_submission_static_analyzer.rules.no_input_func import NoInputFuncRule
from ece241_submission_static_analyzer.rules.no_root_statements import NoRootStatementsRule
