# generated by datamodel-codegen:
#   filename:  AdaptiveDataset.json

from __future__ import annotations
from .base import DtoBaseModel


class AdaptiveDataset(DtoBaseModel):
    dataset_key: str
    file: str
    id: str
