# Generated by ariadne-codegen
# Source: codegen/indexer_status/schema.graphql

from enum import Enum


class Health(str, Enum):
    healthy = "healthy"
    unhealthy = "unhealthy"
    failed = "failed"
